### ISSUE TITLE
"Exception: Can't read response", download does not work anymore

### ISSUE THREAD

**Issue by vauhage** [fraymio/modis-tools#56]
I have downloaded MOD17A2H data successfully until Oct 2nd following the example described by modis-tools. However, now it raises the following error, both for this dataset and the example Nigeria MOD13A2 tiles, both on a server as well as on my desktop computer:

Traceback (most recent call last):
  File "..\miniforge3\envs\gedi\Lib\site-packages\modis_tools\resources.py", line 117, in query
    feed = resp.json()["feed"]
           ~~~~~~~~~~~^^^^^^^^
KeyError: 'feed'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "..\modis_tools_exmaple_script.py", line 23, in <module>
    GranuleHandler.download_from_granules(nigeria_granules, session)
  File "..miniforge3\envs\gedi\Lib\site-packages\modis_tools\granule_handler.py", line 56, in download_from_granules
    urls = [cls.get_url_from_granule(x, ext) for x in granules]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\miniforge3\envs\gedi\Lib\site-packages\modis_tools\resources.py", line 120, in query
    raise Exception("Can't read response") from err
Exception: Can't read response

This is the script I used: 
![grafik](https://github.com/user-attachments/assets/c74272c1-c4c3-430c-8c5d-354b177ecacf)

I am working on Windows with miniforge
![grafik](https://github.com/user-attachments/assets/749b6899-04c8-4098-b490-c1f402068d48)

I would appreciate any help. Thank you very much.

**Comment by mhriris** [comment]
I have same issue!
